name: Run CLI and SDK tests

on: [push]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: [3.11.6, 3.10.12, 3.12.3, 3.9.19]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Go core and run pip install
      run: cd core && pip install -r requirements.txt

    - name: Install dependencies
      run: npm install -g pnpm && pnpm install

    - name: Run tests
      run: pnpm test